### ISSUE TITLE
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by Eurus-Holmes** [zmykevin/A-Visual-Attention-Grounding-Neural-Model#1]
```
Traceback (most recent call last):
  File "nmt_multimodal_beam_DE.py", line 394, in <module>
    train_loss,train_loss_mt,train_loss_vse = train_imagine_beam(batch_x,batch_y,batch_im,batch_x_lengths,imagine_model,optimizer,criterion_mt,criterion_vse,loss_w,teacher_force_ratio,clip=clip)
  File "/A-Visual-Attention-Grounding-Neural-Model-master/train.py", line 43, in train_imagine_beam
    loss,loss_mt,loss_vse = model(input_variable,input_lengths,target_variable,im_variable,teacher_force_ratio,criterion_mt=criterion_mt, criterion_vse=criterion_vse)
```

It occurred error:
```
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED
```

**Comment by Eurus-Holmes** [comment]
In the file: `A-Visual-Attention-Grounding-Neural-Model/machine_translation_vision.yml`

```
- python=3.5.4=h417fded_24
```

But in the README.md, your Prerequisite is Python 3.6?

**Comment by zmykevin** [comment]
Hi, I think I successfully run this pipeline both on python 3.6 and 3.5. The provided conda env file should provide a good virtual environment to run the code. Regarding the CUDA error, one possibility is that the pytorch version is not compatible with the CUDA version that you use right now. I thought I used pytorch 0.3 which was run on CUDA 8.0 or CUD 7.5, but apparently pytorch 0.3 won't really work with CUDA 9.0 or 10.0. Maybe you would need to use a higher version of pytorch and change the code a bit, there should not be too many changes you need to make.

**Comment by Eurus-Holmes** [comment]
@zmykevin Thanks a lot! I have fixed it!
